In [666]:
!pip install nltk

In [667]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter
from torch.utils.data import Dataset,DataLoader
from nltk.tokenize import word_tokenize
import nltk


In [668]:
document = """The Last Train Journey

On a cold winter evening, Daniel arrived at the old railway station carrying a small leather bag.
The station was nearly empty except for a few passengers waiting quietly on wooden benches.
A loud whistle echoed through the air as the final train of the night slowly entered the platform.

Daniel checked the ticket in his pocket and walked toward the train.
The metal doors opened with a creaking sound and warm air rushed outside.
Inside the train, yellow lights flickered softly above rows of empty seats.

He chose a seat beside the window and placed his bag carefully near his feet.
As the train began to move, the city lights slowly disappeared behind thick clouds of fog.
Snow started falling gently outside while distant mountains appeared under the moonlight.

Across the aisle sat an elderly woman reading an old book with a blue cover.
Every few minutes she looked outside the window as if searching for something familiar.
Daniel noticed a silver necklace around her neck shaped like a small compass.

After several hours, the train stopped at a remote station surrounded by tall pine trees.
Very few people entered or left the train at that place.
A strange silence covered the station as the doors closed once again.

Curious about the woman, Daniel finally started a conversation.
The woman introduced herself as Eleanor and explained that she was returning to her hometown after many years.
She said the town was hidden deep within the northern mountains and was known for its beautiful frozen lake.

As the journey continued, Eleanor shared stories from her childhood.
She described colorful festivals, music performances, and lanterns floating across the lake during winter nights.
Daniel listened carefully while the train moved through snowy valleys and dark forests.

Near midnight, the train suddenly slowed down because heavy snow had covered the tracks ahead.
Passengers became nervous and began discussing possible delays.
Conductors moved through the cabins trying to calm everyone.

Daniel looked outside and saw workers removing snow under bright floodlights.
The freezing wind shook the train slightly while snow continued falling from the dark sky.
Despite the delay, Eleanor remained calm and continued telling her stories.

Several hours later, the tracks were finally cleared and the train resumed its journey.
The passengers sighed with relief as warm coffee was served throughout the cabins.
Daniel and Eleanor continued talking about travel, history, and forgotten places around the world.

Just before sunrise, the train reached the mountain town.
The station was small but beautifully decorated with glowing lamps and snow-covered rooftops.
People wearing thick winter coats walked slowly across the icy streets.

Before leaving, Eleanor handed Daniel a folded piece of paper.
Inside it was a drawing of the frozen lake along with a short message thanking him for the conversation.
Daniel smiled and carefully placed the paper inside his notebook.

As the train departed once again, Daniel stood on the platform watching the sunrise over the mountains.
The cold air, quiet streets, and distant church bells created a peaceful atmosphere he would never forget.
Years later, Daniel would still remember that mysterious winter journey and the stories shared by Eleanor on the last train of the night.
"""
     

In [669]:

# NLTK does NOT come with pretrained tokenizers by default.
# Tokenization
nltk.download('punkt')

# Some newer NLTK versions require additional tokenizer tables.
nltk.download('punkt_tab')


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [670]:
tokens=word_tokenize(document.lower())
tokens

['the',
 'last',
 'train',
 'journey',
 'on',
 'a',
 'cold',
 'winter',
 'evening',
 ',',
 'daniel',
 'arrived',
 'at',
 'the',
 'old',
 'railway',
 'station',
 'carrying',
 'a',
 'small',
 'leather',
 'bag',
 '.',
 'the',
 'station',
 'was',
 'nearly',
 'empty',
 'except',
 'for',
 'a',
 'few',
 'passengers',
 'waiting',
 'quietly',
 'on',
 'wooden',
 'benches',
 '.',
 'a',
 'loud',
 'whistle',
 'echoed',
 'through',
 'the',
 'air',
 'as',
 'the',
 'final',
 'train',
 'of',
 'the',
 'night',
 'slowly',
 'entered',
 'the',
 'platform',
 '.',
 'daniel',
 'checked',
 'the',
 'ticket',
 'in',
 'his',
 'pocket',
 'and',
 'walked',
 'toward',
 'the',
 'train',
 '.',
 'the',
 'metal',
 'doors',
 'opened',
 'with',
 'a',
 'creaking',
 'sound',
 'and',
 'warm',
 'air',
 'rushed',
 'outside',
 '.',
 'inside',
 'the',
 'train',
 ',',
 'yellow',
 'lights',
 'flickered',
 'softly',
 'above',
 'rows',
 'of',
 'empty',
 'seats',
 '.',
 'he',
 'chose',
 'a',
 'seat',
 'beside',
 'the',
 'window',
 'a

In [671]:
Counter(tokens)

Counter({'the': 55,
         '.': 39,
         ',': 19,
         'and': 17,
         'a': 16,
         'train': 14,
         'daniel': 11,
         'as': 8,
         'was': 7,
         'of': 6,
         'eleanor': 6,
         'station': 5,
         'with': 5,
         'journey': 4,
         'on': 4,
         'winter': 4,
         'for': 4,
         'his': 4,
         'outside': 4,
         'snow': 4,
         'she': 4,
         'her': 4,
         'continued': 4,
         'at': 3,
         'small': 3,
         'few': 3,
         'passengers': 3,
         'through': 3,
         'air': 3,
         'slowly': 3,
         'inside': 3,
         'carefully': 3,
         'to': 3,
         'while': 3,
         'mountains': 3,
         'across': 3,
         'woman': 3,
         'that': 3,
         'lake': 3,
         'stories': 3,
         'last': 2,
         'cold': 2,
         'old': 2,
         'bag': 2,
         'empty': 2,
         'night': 2,
         'entered': 2,
         'platform': 2,
 

In [672]:
Counter(tokens).values()

dict_values([55, 2, 14, 4, 4, 16, 2, 4, 1, 19, 11, 1, 3, 2, 1, 5, 1, 3, 1, 2, 39, 7, 1, 2, 1, 4, 3, 3, 1, 1, 1, 1, 1, 1, 1, 3, 3, 8, 1, 6, 2, 3, 2, 2, 1, 1, 1, 4, 1, 17, 2, 1, 1, 2, 1, 5, 1, 1, 2, 1, 4, 3, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 3, 2, 1, 2, 3, 1, 1, 1, 1, 2, 1, 1, 4, 2, 2, 1, 3, 2, 3, 1, 2, 1, 3, 1, 1, 2, 1, 3, 1, 1, 1, 1, 1, 1, 4, 2, 1, 1, 1, 1, 1, 1, 1, 2, 4, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 3, 1, 1, 1, 2, 1, 2, 2, 1, 2, 2, 2, 1, 1, 6, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 3, 4, 2, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1])

## Build Vocab

In [673]:
#build vocab
vocab={'<unk>':0}

In [674]:
for token in Counter(tokens).keys():
    if token not in vocab:
        vocab[token]= len(vocab)

vocab

{'<unk>': 0,
 'the': 1,
 'last': 2,
 'train': 3,
 'journey': 4,
 'on': 5,
 'a': 6,
 'cold': 7,
 'winter': 8,
 'evening': 9,
 ',': 10,
 'daniel': 11,
 'arrived': 12,
 'at': 13,
 'old': 14,
 'railway': 15,
 'station': 16,
 'carrying': 17,
 'small': 18,
 'leather': 19,
 'bag': 20,
 '.': 21,
 'was': 22,
 'nearly': 23,
 'empty': 24,
 'except': 25,
 'for': 26,
 'few': 27,
 'passengers': 28,
 'waiting': 29,
 'quietly': 30,
 'wooden': 31,
 'benches': 32,
 'loud': 33,
 'whistle': 34,
 'echoed': 35,
 'through': 36,
 'air': 37,
 'as': 38,
 'final': 39,
 'of': 40,
 'night': 41,
 'slowly': 42,
 'entered': 43,
 'platform': 44,
 'checked': 45,
 'ticket': 46,
 'in': 47,
 'his': 48,
 'pocket': 49,
 'and': 50,
 'walked': 51,
 'toward': 52,
 'metal': 53,
 'doors': 54,
 'opened': 55,
 'with': 56,
 'creaking': 57,
 'sound': 58,
 'warm': 59,
 'rushed': 60,
 'outside': 61,
 'inside': 62,
 'yellow': 63,
 'lights': 64,
 'flickered': 65,
 'softly': 66,
 'above': 67,
 'rows': 68,
 'seats': 69,
 'he': 70,
 'chose

In [675]:
len(vocab)

284

### Extract Sentence from data

In [676]:
document.split('\n')

['The Last Train Journey',
 '',
 'On a cold winter evening, Daniel arrived at the old railway station carrying a small leather bag.',
 'The station was nearly empty except for a few passengers waiting quietly on wooden benches.',
 'A loud whistle echoed through the air as the final train of the night slowly entered the platform.',
 '',
 'Daniel checked the ticket in his pocket and walked toward the train.',
 'The metal doors opened with a creaking sound and warm air rushed outside.',
 'Inside the train, yellow lights flickered softly above rows of empty seats.',
 '',
 'He chose a seat beside the window and placed his bag carefully near his feet.',
 'As the train began to move, the city lights slowly disappeared behind thick clouds of fog.',
 'Snow started falling gently outside while distant mountains appeared under the moonlight.',
 '',
 'Across the aisle sat an elderly woman reading an old book with a blue cover.',
 'Every few minutes she looked outside the window as if searching for

In [677]:
input_sentences=document.split('\n')

In [678]:
input_sentences[3]

'The station was nearly empty except for a few passengers waiting quietly on wooden benches.'

In [679]:
for sentence in input_sentences:
    print(word_tokenize(sentence.lower()))

['the', 'last', 'train', 'journey']
[]
['on', 'a', 'cold', 'winter', 'evening', ',', 'daniel', 'arrived', 'at', 'the', 'old', 'railway', 'station', 'carrying', 'a', 'small', 'leather', 'bag', '.']
['the', 'station', 'was', 'nearly', 'empty', 'except', 'for', 'a', 'few', 'passengers', 'waiting', 'quietly', 'on', 'wooden', 'benches', '.']
['a', 'loud', 'whistle', 'echoed', 'through', 'the', 'air', 'as', 'the', 'final', 'train', 'of', 'the', 'night', 'slowly', 'entered', 'the', 'platform', '.']
[]
['daniel', 'checked', 'the', 'ticket', 'in', 'his', 'pocket', 'and', 'walked', 'toward', 'the', 'train', '.']
['the', 'metal', 'doors', 'opened', 'with', 'a', 'creaking', 'sound', 'and', 'warm', 'air', 'rushed', 'outside', '.']
['inside', 'the', 'train', ',', 'yellow', 'lights', 'flickered', 'softly', 'above', 'rows', 'of', 'empty', 'seats', '.']
[]
['he', 'chose', 'a', 'seat', 'beside', 'the', 'window', 'and', 'placed', 'his', 'bag', 'carefully', 'near', 'his', 'feet', '.']
['as', 'the', 'train

In [680]:
def text_to_indices(sentence,vocab):
    numerical_sentences=[]
    for token in sentence:
        if token in vocab:
            numerical_sentences.append(vocab[token])
        else:
            numerical_sentences.append(vocab['<unk>'])
    return numerical_sentences

In [681]:
input_numerical_sentence=[]
for sentence in input_sentences:
    input_numerical_sentence.append(text_to_indices(word_tokenize(sentence.lower()),vocab))

In [682]:
input_numerical_sentence

[[1, 2, 3, 4],
 [],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20, 21],
 [1, 16, 22, 23, 24, 25, 26, 6, 27, 28, 29, 30, 5, 31, 32, 21],
 [6, 33, 34, 35, 36, 1, 37, 38, 1, 39, 3, 40, 1, 41, 42, 43, 1, 44, 21],
 [],
 [11, 45, 1, 46, 47, 48, 49, 50, 51, 52, 1, 3, 21],
 [1, 53, 54, 55, 56, 6, 57, 58, 50, 59, 37, 60, 61, 21],
 [62, 1, 3, 10, 63, 64, 65, 66, 67, 68, 40, 24, 69, 21],
 [],
 [70, 71, 6, 72, 73, 1, 74, 50, 75, 48, 20, 76, 77, 48, 78, 21],
 [38, 1, 3, 79, 80, 81, 10, 1, 82, 64, 42, 83, 84, 85, 86, 40, 87, 21],
 [88, 89, 90, 91, 61, 92, 93, 94, 95, 96, 1, 97, 21],
 [],
 [98, 1, 99, 100, 101, 102, 103, 104, 101, 14, 105, 56, 6, 106, 107, 21],
 [108, 27, 109, 110, 111, 61, 1, 74, 38, 112, 113, 26, 114, 115, 21],
 [11, 116, 6, 117, 118, 119, 120, 121, 122, 123, 6, 18, 124, 21],
 [],
 [125, 126, 127, 10, 1, 3, 128, 13, 6, 129, 16, 130, 131, 132, 133, 134, 21],
 [135, 27, 136, 43, 137, 138, 1, 3, 13, 139, 140, 21],
 [6, 141, 142, 143, 1, 16, 38, 1, 54, 144, 145, 146

## Training Sequence form

In [683]:
training_sequence = []
for sentence in input_numerical_sentence:
  for i in range(1,len(sentence)):
    training_sequence.append(sentence[:i+1])

In [684]:
training_sequence

[[1, 2],
 [1, 2, 3],
 [1, 2, 3, 4],
 [5, 6],
 [5, 6, 7],
 [5, 6, 7, 8],
 [5, 6, 7, 8, 9],
 [5, 6, 7, 8, 9, 10],
 [5, 6, 7, 8, 9, 10, 11],
 [5, 6, 7, 8, 9, 10, 11, 12],
 [5, 6, 7, 8, 9, 10, 11, 12, 13],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20, 21],
 [1, 16],
 [1, 16, 22],
 [1, 16, 22, 23],
 [1, 16, 22, 23, 24],
 [1, 16, 22, 23, 24, 25],
 [1, 16, 22, 23, 24, 25, 26],
 [1, 16, 22, 23, 24, 25, 26, 6],
 [1, 16, 22, 23, 24, 25, 26, 6, 27],
 [1, 16, 22, 23, 24, 25, 26, 6, 27, 28],
 [1, 16, 22, 23, 24, 2

In [685]:
training_sequence[:5]

[[1, 2], [1, 2, 3], [1, 2, 3, 4], [5, 6], [5, 6, 7]]

In [686]:
len_list=[]
for sequence in training_sequence:
    len_list.append(len(sequence))

In [687]:
max(len_list)

25

In [688]:
#Logic
[0]*(max(len_list)-len(sequence))

[]

In [689]:
training_sequence[0]

[1, 2]

In [690]:
padded_training_sequence=[]
for sequence in training_sequence:
    padded_training_sequence.append([0]*(max(len_list)-len(sequence))+sequence)

In [691]:
len(padded_training_sequence[0])

25

In [692]:
padded_training_sequence

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 8],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 8, 9],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 8, 9, 10],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 8, 9, 10, 11],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
 

In [693]:
padded_training_sequence[2]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4]

In [694]:
max(padded_training_sequence)

[158,
 223,
 10,
 11,
 278,
 281,
 282,
 139,
 283,
 8,
 4,
 50,
 1,
 172,
 171,
 131,
 153,
 5,
 1,
 2,
 3,
 40,
 1,
 41,
 21]

#### Tensor convert

In [695]:
padded_training_sequence=torch.tensor(padded_training_sequence,dtype=torch.long)

In [696]:
padded_training_sequence

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   2,   3,   4],
        ...,
        [  0,   0, 158,  ...,   3,  40,   1],
        [  0, 158, 223,  ...,  40,   1,  41],
        [158, 223,  10,  ...,   1,  41,  21]])

In [697]:
X = padded_training_sequence[:, :-1]

In [698]:
X

tensor([[  0,   0,   0,  ...,   0,   0,   1],
        [  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        ...,
        [  0,   0, 158,  ...,   2,   3,  40],
        [  0, 158, 223,  ...,   3,  40,   1],
        [158, 223,  10,  ...,  40,   1,  41]])

In [699]:
y = padded_training_sequence[:, -1]

In [700]:
y

tensor([  2,   3,   4,   6,   7,   8,   9,  10,  11,  12,  13,   1,  14,  15,
         16,  17,   6,  18,  19,  20,  21,  16,  22,  23,  24,  25,  26,   6,
         27,  28,  29,  30,   5,  31,  32,  21,  33,  34,  35,  36,   1,  37,
         38,   1,  39,   3,  40,   1,  41,  42,  43,   1,  44,  21,  45,   1,
         46,  47,  48,  49,  50,  51,  52,   1,   3,  21,  53,  54,  55,  56,
          6,  57,  58,  50,  59,  37,  60,  61,  21,   1,   3,  10,  63,  64,
         65,  66,  67,  68,  40,  24,  69,  21,  71,   6,  72,  73,   1,  74,
         50,  75,  48,  20,  76,  77,  48,  78,  21,   1,   3,  79,  80,  81,
         10,   1,  82,  64,  42,  83,  84,  85,  86,  40,  87,  21,  89,  90,
         91,  61,  92,  93,  94,  95,  96,   1,  97,  21,   1,  99, 100, 101,
        102, 103, 104, 101,  14, 105,  56,   6, 106, 107,  21,  27, 109, 110,
        111,  61,   1,  74,  38, 112, 113,  26, 114, 115,  21, 116,   6, 117,
        118, 119, 120, 121, 122, 123,   6,  18, 124,  21, 126, 1

In [701]:
len(X)

555

In [702]:
len(y)

555

#### Custom dataset and dataloader

In [703]:
class CustomDataset(Dataset):
  def __init__(self,X,y):
    self.X = X
    self.y = y

  def __len__(self):
    return self.X.shape[0]

  def __getitem__(self, idx) :
    return self.X[idx], self.y[idx]

In [704]:
dataset = CustomDataset(X,y)

In [705]:
len(dataset)

555

In [706]:
dataloader = DataLoader(dataset,batch_size=32,shuffle=True)

In [707]:
for input , output in dataloader:
  print(input,output)

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0, 135,  27, 136,  43],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0, 110, 175, 176, 177,  10,
         178, 179,  10,  50, 180, 181,  98,   1, 169, 182],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  62, 259,  22,   6,
         260,  40,   1, 168, 169, 261,  56,   6, 262, 263],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   6],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,  11,  50, 153, 170, 232, 148, 233],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0, 136, 250,  85,   8, 251,  51,  42,  98],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   5,   6,   7,   8,   9,  10,  11],
        [  0,   0,   0,   0

In [708]:
X[0]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [709]:
X[554]

tensor([158, 223,  10,  11, 278, 281, 282, 139, 283,   8,   4,  50,   1, 172,
        171, 131, 153,   5,   1,   2,   3,  40,   1,  41])

In [710]:
#X[555]

In [711]:
len(dataset)

555

In [712]:
len(vocab)

284

In [713]:
len(dataset[0])

2

In [714]:
len(dataset[0][0])

24

In [715]:
dataset[0]

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 tensor(2))

#### LSTM Cell

In [716]:
class LSTMModel(nn.Module):
    def __init__(self,vocab_size):
        super().__init__()
        self.embedding=nn.Embedding(vocab_size,100)
        self.lstm=nn.LSTM(100,150,batch_first=True)
        self.fc=nn.Linear(150,vocab_size) 
        
    def forward(self,x):
        embedded=self.embedding(x)
        intermediate_hidden_states,(final_hidden_states,final_cell_state)=self.lstm(embedded)
        output=self.fc(final_hidden_states.squeeze(0))
        return output

In [717]:
model=LSTMModel(len(vocab))

In [718]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [719]:
model.to(device)

LSTMModel(
  (embedding): Embedding(284, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=284, bias=True)
)

In [720]:
len(vocab)

284

In [721]:
x=nn.Embedding(284,100)
y=nn.LSTM(100,150,batch_first=True)
z=nn.Linear(150,284)

In [722]:
dataset[0][0].shape

torch.Size([24])

In [723]:
dataset[0][0].unsqueeze(0).shape

torch.Size([1, 24])

In [724]:
a=dataset[0][0].unsqueeze(0)
a

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [725]:
x(a)

tensor([[[ 1.2221,  1.1345,  0.4202,  ...,  0.0402,  1.6433,  1.8232],
         [ 1.2221,  1.1345,  0.4202,  ...,  0.0402,  1.6433,  1.8232],
         [ 1.2221,  1.1345,  0.4202,  ...,  0.0402,  1.6433,  1.8232],
         ...,
         [ 1.2221,  1.1345,  0.4202,  ...,  0.0402,  1.6433,  1.8232],
         [ 1.2221,  1.1345,  0.4202,  ...,  0.0402,  1.6433,  1.8232],
         [ 0.7239,  2.0644,  0.7249,  ..., -0.1498, -0.6233,  2.2819]]],
       grad_fn=<EmbeddingBackward0>)

In [726]:
x(a).shape

torch.Size([1, 24, 100])

In [727]:
b = x(a)

In [728]:
y(b)

(tensor([[[-0.0975,  0.0319,  0.0347,  ...,  0.0635,  0.0639,  0.0921],
          [-0.1216,  0.0530,  0.0525,  ...,  0.0852,  0.0982,  0.1530],
          [-0.1278,  0.0644,  0.0612,  ...,  0.0868,  0.1155,  0.1911],
          ...,
          [-0.1302,  0.0817,  0.0683,  ...,  0.0527,  0.1328,  0.2546],
          [-0.1302,  0.0817,  0.0683,  ...,  0.0527,  0.1328,  0.2546],
          [-0.1297,  0.1050,  0.0615,  ...,  0.1149, -0.0567,  0.2671]]],
        grad_fn=<TransposeBackward0>),
 (tensor([[[-0.1297,  0.1050,  0.0615, -0.0913,  0.1430,  0.0054, -0.0981,
            -0.0669, -0.1227, -0.0534, -0.2080, -0.2340, -0.0099,  0.3143,
            -0.0734, -0.0261,  0.1309, -0.1238, -0.1138,  0.0859,  0.1577,
             0.0776, -0.0533,  0.1671, -0.0491, -0.2181,  0.0164,  0.1403,
            -0.1092,  0.1635, -0.1791, -0.0953, -0.3080,  0.0290, -0.3492,
            -0.0700, -0.0136,  0.2760, -0.2392, -0.0928,  0.0676, -0.0845,
             0.1292,  0.0606,  0.0574,  0.0010, -0.0045,  0.03

In [729]:
len(y(b))

2

In [730]:
c ,d = y(b)

In [731]:
c.shape  #Set of all intermediate hidden state

torch.Size([1, 24, 150])

In [732]:
len(y(b))

2

In [733]:
len(d)

2

In [734]:
e, f = d

In [735]:
e.shape  #Cell state

torch.Size([1, 1, 150])

In [736]:
f.shape

torch.Size([1, 1, 150])

In [737]:
f_temp = f.squeeze(0).shape
f_temp

torch.Size([1, 150])

In [738]:
f_temp = f.squeeze(0)

In [739]:
z(f_temp)

tensor([[-6.4070e-02, -9.9423e-02, -1.8234e-01, -3.5242e-02,  8.2696e-02,
          1.3113e-01, -7.0599e-02,  2.6707e-02,  2.3456e-01,  1.2314e-01,
          4.1748e-02,  2.5040e-04,  1.7344e-01, -2.9773e-01,  2.5497e-02,
          5.1952e-01, -1.7244e-01, -4.8432e-02,  3.0943e-02, -1.2786e-02,
         -4.9093e-02,  3.8254e-01,  1.6434e-01, -2.9714e-02,  1.1461e-01,
         -1.2839e-01,  7.2409e-02,  1.6358e-01,  3.1764e-01, -2.2161e-02,
          9.6513e-02, -2.1260e-02, -3.1655e-01, -3.2158e-01, -1.2632e-01,
          1.3653e-01,  3.3386e-01,  2.3634e-01, -2.5443e-02, -1.0073e-01,
          2.0723e-01,  6.4086e-01, -2.2881e-01,  1.7440e-01,  4.4771e-02,
         -7.0898e-02,  6.1580e-02, -1.2413e-02, -2.2064e-02, -1.8327e-01,
         -8.8600e-03, -1.2282e-01,  7.6176e-02,  1.9314e-04, -6.4882e-02,
         -2.2419e-01, -1.6654e-01, -1.9809e-01,  1.3678e-01, -1.4486e-01,
          1.6033e-01, -2.9815e-01,  2.1523e-01,  1.7714e-01,  1.5220e-01,
         -6.1412e-02, -4.1957e-02,  8.

In [740]:
len(f_temp[0])

150

In [741]:
len(z(f_temp)[0])

284

In [742]:
len(vocab)

284

In [743]:
for batch_x , batch_y in dataloader:
  print(batch_x, batch_y)

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,  62,   1,   3,  10,  63,  64],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  11,  45,
           1,  46,  47,  48,  49,  50,  51,  52,   1,   3],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,  11, 266],
        [  0,   0,   0,   0,   0,   0,  62, 259,  22,   6, 260,  40,   1, 168,
         169, 261,  56,   6, 262, 263, 264, 265,  26,   1],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0, 125, 126],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0, 158, 223,  10,  11, 278, 281],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,  38,   1,   3,  79,  80,
          81,  10,   1,  82,  64,  42,  83,  84,  85,  86],
        [  0,   0,   0,   0

In [744]:
for params in model.parameters():
    print(params)

Parameter containing:
tensor([[ 0.4672, -1.0079,  0.1060,  ...,  2.1926,  0.0046,  0.5053],
        [ 0.6428,  0.3689,  1.1161,  ..., -0.8441,  1.2742,  0.1674],
        [ 0.5920, -1.4652,  0.8731,  ..., -1.7541,  1.0369,  2.2147],
        ...,
        [-1.1394,  0.0101,  1.9559,  ...,  1.8264,  0.6148,  0.7078],
        [ 1.6024,  0.1271,  0.4289,  ...,  1.2508, -1.2681,  0.2362],
        [ 0.3812,  0.7810, -0.3853,  ...,  0.3979,  2.4473,  2.3849]],
       requires_grad=True)
Parameter containing:
tensor([[ 0.0314, -0.0079, -0.0789,  ..., -0.0545, -0.0316, -0.0056],
        [ 0.0037,  0.0221, -0.0472,  ..., -0.0093, -0.0053,  0.0034],
        [ 0.0334, -0.0312, -0.0725,  ..., -0.0520, -0.0168, -0.0615],
        ...,
        [ 0.0697,  0.0337,  0.0196,  ..., -0.0250, -0.0783, -0.0569],
        [ 0.0438, -0.0575, -0.0207,  ...,  0.0114, -0.0438,  0.0363],
        [-0.0139, -0.0714, -0.0253,  ..., -0.0315, -0.0614, -0.0660]],
       requires_grad=True)
Parameter containing:
tensor([[-0.

In [745]:
for batch_x,batch_y in dataloader:
    print(batch_x,batch_y)

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          77, 190,  10,   1,   3, 191, 192, 193, 194, 195],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,  11, 111,  61,  50, 209, 210, 211],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,  98,   1,  99, 100, 101, 102, 103],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           1,  16,  22,  18, 243, 244, 245,  56, 246, 247],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  77,
         190,  10,   1,   3, 191, 192, 193, 194, 195,  88],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   1, 214, 215, 216,   1,   3, 217,  92,  88],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,  11, 184,  76,  92,   1],
        [  0,   0,   0,   0

## Training loop

In [746]:
epochs=50
learning_rate=0.001
criterion=nn.CrossEntropyLoss()

In [747]:
optimizer=torch.optim.Adam(model.parameters(),lr=learning_rate)

In [748]:
# training loop

for epoch in range(epochs):
  total_loss = 0

  for batch_x, batch_y in dataloader:

    batch_x, batch_y = batch_x.to(device), batch_y.to(device)

    optimizer.zero_grad()

    output = model(batch_x)

    loss = criterion(output, batch_y)

    loss.backward()

    optimizer.step()

    total_loss = total_loss + loss.item()

  print(f"Epoch: {epoch + 1}, Loss: {total_loss:.4f}")

Epoch: 1, Loss: 101.0235
Epoch: 2, Loss: 93.9719
Epoch: 3, Loss: 86.9325
Epoch: 4, Loss: 81.9026
Epoch: 5, Loss: 76.8606
Epoch: 6, Loss: 71.0126
Epoch: 7, Loss: 64.8202
Epoch: 8, Loss: 59.9088
Epoch: 9, Loss: 54.8028
Epoch: 10, Loss: 49.3564
Epoch: 11, Loss: 44.2662
Epoch: 12, Loss: 40.2162
Epoch: 13, Loss: 35.7893
Epoch: 14, Loss: 31.6583
Epoch: 15, Loss: 28.1859
Epoch: 16, Loss: 24.5344
Epoch: 17, Loss: 21.7236
Epoch: 18, Loss: 19.6096
Epoch: 19, Loss: 17.1214
Epoch: 20, Loss: 15.2811
Epoch: 21, Loss: 13.6507
Epoch: 22, Loss: 12.2604
Epoch: 23, Loss: 11.0830
Epoch: 24, Loss: 9.9764
Epoch: 25, Loss: 8.9285
Epoch: 26, Loss: 8.3792
Epoch: 27, Loss: 7.5243
Epoch: 28, Loss: 6.8826
Epoch: 29, Loss: 6.3529
Epoch: 30, Loss: 5.9133
Epoch: 31, Loss: 5.5357
Epoch: 32, Loss: 5.2084
Epoch: 33, Loss: 4.9510
Epoch: 34, Loss: 4.7612
Epoch: 35, Loss: 4.4802
Epoch: 36, Loss: 4.1541
Epoch: 37, Loss: 4.0854
Epoch: 38, Loss: 3.8115
Epoch: 39, Loss: 3.5764
Epoch: 40, Loss: 3.4768
Epoch: 41, Loss: 3.3307
E

# Prediction

In [749]:
max(len_list)

25

In [750]:
#logic
[0]* (max(len_list)-len(sequence))

[]

In [751]:
def prediction(model,vocab,text):

    #tokenize
    tokenized_text = word_tokenize(text.lower())

    # print(tokenized_text)


    #numerical indices
    numerical_text = text_to_indices(tokenized_text,vocab)

    # print(numerical_text)

    #padding
    padded_text = torch.tensor([0]* (25-len(numerical_text)) + numerical_text , dtype=torch.long).unsqueeze(0)

    # print(padded_text)

    # print(len(padded_text))

    # print(padded_text.shape)


    #send to model
    output = model(padded_text)

    # print("model's output",output)

    # print("printing total_elements",len(output[0]))

    #predicted index

    value, index = torch.max(output,dim=1)

    #print(f"printing value and index {value}, {index}")

    #print(f"printing  index  {index}")

    #print("printing the word ")

    #print(list(vocab.keys())[index])
  
    #merge with text

    return text + " " + list(vocab.keys())[index]

In [752]:
prediction(model,vocab,"The last train journey")

'The last train journey and'

In [753]:
len(vocab)

284

In [754]:
document.split('\n')

['The Last Train Journey',
 '',
 'On a cold winter evening, Daniel arrived at the old railway station carrying a small leather bag.',
 'The station was nearly empty except for a few passengers waiting quietly on wooden benches.',
 'A loud whistle echoed through the air as the final train of the night slowly entered the platform.',
 '',
 'Daniel checked the ticket in his pocket and walked toward the train.',
 'The metal doors opened with a creaking sound and warm air rushed outside.',
 'Inside the train, yellow lights flickered softly above rows of empty seats.',
 '',
 'He chose a seat beside the window and placed his bag carefully near his feet.',
 'As the train began to move, the city lights slowly disappeared behind thick clouds of fog.',
 'Snow started falling gently outside while distant mountains appeared under the moonlight.',
 '',
 'Across the aisle sat an elderly woman reading an old book with a blue cover.',
 'Every few minutes she looked outside the window as if searching for

### Generate Automatically

In [755]:
import time
num_tokens=20
input_text='Daniel checked the ticket'

for i in range(num_tokens):
    output_text=prediction(model,vocab,input_text)
    print(output_text)
    input_text = output_text
    time.sleep(0.5)

Daniel checked the ticket in
Daniel checked the ticket in his
Daniel checked the ticket in his pocket
Daniel checked the ticket in his pocket and
Daniel checked the ticket in his pocket and walked
Daniel checked the ticket in his pocket and walked toward
Daniel checked the ticket in his pocket and walked toward the
Daniel checked the ticket in his pocket and walked toward the train
Daniel checked the ticket in his pocket and walked toward the train .
Daniel checked the ticket in his pocket and walked toward the train . .
Daniel checked the ticket in his pocket and walked toward the train . . .
Daniel checked the ticket in his pocket and walked toward the train . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . . . . .

## Accuracy calculation

In [766]:
def calculate_accuracy(model,dataloader,device):
    model.eval() #set the model to evaluation mode
    correct=0
    total=0
    
    with torch.no_grad():
        for batch_x,batch_y in dataloader:
            # print(batch_x,batch_y)
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)
            #get model prediction
            output = model(batch_x)

            print(len(output[0]))

            #get the predictec word indices
            _,predicted=torch.max(output,dim=1)
            print(predicted)
            
            #compare wityh actual label

            # print("printing y lable",batch_y)

            # print(predicted == batch_y)
            correct += (predicted == batch_y).sum().item()

            # print(correct)
            # print("working with total",batch_y.size())
            total += batch_y.size(0)

        accuracy = correct / total * 100
        return accuracy

In [768]:
accuracy = calculate_accuracy(model,dataloader,device)

print(f" Model accuracy {accuracy :.2f}%")

284
tensor([ 76, 237,  10,  68,   1, 121, 138, 193,   6, 156, 205,  26, 243, 240,
         21,  81,   1, 109,   8,  21,   1, 274,  51, 131,   7, 112,   6,  48,
         50, 157,  21, 220])
284
tensor([242,  90, 110, 249,  21, 168, 168, 188,  22,  39,  50, 180, 115, 229,
        153,   4, 173, 188,  36,  36, 175, 126,  43,  79,  21, 266,  21, 140,
        213,  31, 263, 119])
284
tensor([ 10,   8,  10, 133, 148, 143, 200,  21, 197,  21,  89, 231,  75,  26,
         10, 224, 186,   6,  77,  56,  73,  41,  85, 233,  56,   1, 266,  72,
          9, 276, 173,  21])
284
tensor([ 21,  88, 172, 134,   1,   1,  11, 120,   3,   3,  21,  42, 230,  71,
         54, 174,   1, 143,  80,   1, 146,  16,  28, 275,   1, 146, 153,  99,
          1,  21, 144,  26])
284
tensor([171,  27, 271,  22, 187,  22,   6, 246,   4,  13, 279, 278, 165, 105,
         30,  10, 139, 129, 150, 169, 110,  21,  14,  10, 113, 218, 266, 101,
         21, 192,  54, 120])
284
tensor([  6,   1,  21, 266,  76,  69, 280, 261, 179